from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os


def generate_pdf(
    student_name,
    roll_number,
    subject,
    section,
    transcript,
    similarity,
    features,
    final_score,
    feedback,
    output_path="reports/Concept_Report.pdf"
):

    # Create reports folder if it doesn't exist
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    c = canvas.Canvas(output_path, pagesize=letter)

    width, height = letter
    y = height - 50

    # ---------------------------------
    # Title
    # ---------------------------------
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "Voice Based Concept Understanding Analyser")

    y -= 40

    # ---------------------------------
    # Student Details
    # ---------------------------------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Student Details")

    y -= 20

    c.setFont("Helvetica", 12)

    c.drawString(50, y, f"Student Name : {student_name}")
    y -= 20

    c.drawString(50, y, f"Roll Number : {roll_number}")
    y -= 20

    c.drawString(50, y, f"Subject : {subject}")
    y -= 20

    c.drawString(50, y, f"Section : {section}")

    y -= 35

    # ---------------------------------
    # Transcript
    # ---------------------------------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Transcript")

    y -= 20

    c.setFont("Helvetica", 11)

    words = transcript.split()
    line = ""

    for word in words:
        if len(line + word) < 90:
            line += word + " "
        else:
            c.drawString(50, y, line)
            y -= 18
            line = word + " "

            if y < 60:
                c.showPage()
                c.setFont("Helvetica", 11)
                y = height - 50

    c.drawString(50, y, line)

    y -= 40

    # If transcript is too long
    if y < 160:
        c.showPage()
        y = height - 50

    # ---------------------------------
    # Evaluation
    # ---------------------------------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Evaluation")

    y -= 25

    c.setFont("Helvetica", 12)

    c.drawString(50, y, f"Semantic Similarity : {similarity:.2f}%")
    y -= 20

    c.drawString(50, y, f"Duration : {features['duration']} sec")
    y -= 20

    c.drawString(50, y, f"Speech Rate : {features['speech_rate']} WPM")
    y -= 20

    c.drawString(50, y, f"Energy : {features['energy']}")
    y -= 20

    c.drawString(50, y, f"Final Score : {final_score:.2f}/100")
    y -= 20

    c.drawString(50, y, f"Feedback : {feedback}")

    y -= 40

    # ---------------------------------
    # Footer
    # ---------------------------------
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(
        50,
        y,
        "Generated by Voice Based Concept Understanding Analyser"
    )

    c.save()

    return output_path